### PR TITLE
Compatibility with GHC 8.2 and Cabal 2.0.

### PR DESCRIPTION
**Pull request by nh2**
I have not cared to keep backwards compatibility in this commit.

### CODE REVIEW

**Comment by l29ah** [comment]
```
source/Network/Xmpp/Stream.hs:753:52: error:
    • Couldn't match type ‘Int’ with ‘Word16’
      Expected type: [(Word16, Word16, Word16, Domain)]
        Actual type: [(Int, Int, Int, Domain)]
    • In the first argument of ‘orderSrvResult’, namely ‘srvResult'’
      In a stmt of a 'do' block:
        orderedSrvResult <- orderSrvResult srvResult'
      In the expression:
        do debugM "Pontarius.Xmpp" $ "SRV result: " ++ (show srvResult')
           orderedSrvResult <- orderSrvResult srvResult'
           return
             $ Just
                 $ map (\ (_, _, port, domain) -> (domain, port)) orderedSrvResult
    |
753 |                 orderedSrvResult <- orderSrvResult srvResult'
    |                                                    ^^^^^^^^^^
```

**Comment by Philonous** [comment]
What lts is that on? It seems to build fine here (lts-10.4)

**Comment by l29ah** [comment]
I've just jumped to ghc-8.2.2. dns-2.0.13 here, maybe the lower bound in cabal should be bumped.

**Comment by nh2** [comment]
> I've just jumped to ghc-8.2.2. dns-2.0.13 was here; the lower bound in cabal should be bumped.

@l29ah This is probably true, but I think it is independent from my change in this PR; I think the lower bound was set too low already before my change (would be nice if you could confirm that).

**Comment by l29ah** [comment]
No, it's all your fault :P

**Pull request merged**
